

export const USER_SIGNIN_API = 'USER_SIGNIN_API'


export const GET_ALL_PROJECT_CATE = 'GET_ALL_PROJECT_CATE'
export const GET_ALL_PROJECT_CATE_ACTION ='GET_ALL_PROJECT_CATE_ACTION'
export const CREATE_PROJECT_AUTHOR = 'CREATE_PROJECT_AUTHOR'


// project
export const GET_ALL_PROJECT_MANA_ACTION = 'GET_ALL_PROJECT_MANA_ACTION'
export const SET_PROJECT_MANA_ON_REDUCER = 'SET_PROJECT_MANA_ON_REDUCER'