
export const GET_TASK_API = 'GET_TASK_API'
export const DELETE_TASK_API = 'DELETE_TASK_API'
export const ADD_TASK_API = 'ADD_TASK_API'

//saga
export const ACTIVE_LOADING = 'ACTIVE_LOADING'
export const HIDE_LOADING = 'HIDE_LOADING'
export const GET_TASK_API_ACTION = 'GET_TASK_API_ACTION'
export const DEL_TASK_API_ACTION = 'DEL_TASK_API_ACTION'
export const ADD_TASK_API_ACTION = 'ADD_TASK_API_ACTION'
export const PUT_TASK_API_ACTION = 'PUT_TASK_API_ACTION'
export const REJECT_TASK_API_ACTION = 'REJECT_TASK_API_ACTION'


